eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:9092/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-projet
          uri: lb://microservice-projet
          predicates:
           - path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>,*),/$\{path}
      
